# Dataframe = A tabular data structure with rows and columns (2D). Similar to an excel spreadsheet

import pandas as pd

data = {
    "Name": ["Sponge Bob", "Patrick", "Squidward"],
    "Age": [30, 35, 50]
}

dataframe = pd.DataFrame(data, index=["Employee 1", "Employee 2", "Employee 3"]) #D and F in "DataFrame" is a constructor and not a function
# the index is generated by default and starts with zero. we can add our own index after "data" above

#Add a new column
dataframe["Job"] = ["Burger dude", "N/A", "Cashier"]

# add a new row
new_row = pd.DataFrame([{"Name": "Sandy", "Age": 28, "Job": "Engineer"}, #this is going to be concatenated
                             {"Name": "Mr. krabbs", "Age": 60, "Job": "Manager"}], #We add another employee
                             index=["Employee 4", "Employee 5"],)
dataframe = pd.concat([dataframe, new_row]) #we want to concatenate our dataframe variable with the new row

print(dataframe)
print()
print(dataframe.loc["Employee 3"])
print(dataframe.iloc[0]) #we use iloc for the original index location
















